// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.DbContexts;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(PokemonBinderContext))]
    [Migration("20260119004137_PokemonBinderDBInitialMigration")]
    partial class PokemonBinderDBInitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("api.Entities.Binder", b =>
                {
                    b.Property<int>("BinderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BinderId");

                    b.ToTable("Binders");
                });

            modelBuilder.Entity("api.Entities.PokemonCard", b =>
                {
                    b.Property<int>("PokemonCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BinderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Set")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PokemonCardId");

                    b.HasIndex("BinderId");

                    b.ToTable("PokemonCards");
                });

            modelBuilder.Entity("api.Entities.PokemonCard", b =>
                {
                    b.HasOne("api.Entities.Binder", "Binder")
                        .WithMany("PokemonCard")
                        .HasForeignKey("BinderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Binder");
                });

            modelBuilder.Entity("api.Entities.Binder", b =>
                {
                    b.Navigation("PokemonCard");
                });
#pragma warning restore 612, 618
        }
    }
}
