// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.DbContexts;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(PokemonBinderContext))]
    partial class PokemonBinderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("api.Entities.Binder", b =>
                {
                    b.Property<int>("BinderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BinderId");

                    b.ToTable("Binders");

                    b.HasData(
                        new
                        {
                            BinderId = 1,
                            Name = "Obtained"
                        },
                        new
                        {
                            BinderId = 2,
                            Name = "Wishlist"
                        });
                });

            modelBuilder.Entity("api.Entities.PokemonCard", b =>
                {
                    b.Property<int>("PokemonCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BinderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Set")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PokemonCardId");

                    b.HasIndex("BinderId");

                    b.ToTable("PokemonCards");

                    b.HasData(
                        new
                        {
                            PokemonCardId = 1,
                            BinderId = 2,
                            Name = "Sylveon GX",
                            Number = "SV76/SV94",
                            Set = "Hidden Fates"
                        },
                        new
                        {
                            PokemonCardId = 2,
                            BinderId = 1,
                            Name = "N's Zorua",
                            Number = "SVP189",
                            Set = "Journey Together"
                        },
                        new
                        {
                            PokemonCardId = 3,
                            BinderId = 1,
                            Name = "Yamper on Bed",
                            Number = "099/094",
                            Set = "Phantasmal Flames"
                        });
                });

            modelBuilder.Entity("api.Entities.PokemonCard", b =>
                {
                    b.HasOne("api.Entities.Binder", "Binder")
                        .WithMany("PokemonCard")
                        .HasForeignKey("BinderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Binder");
                });

            modelBuilder.Entity("api.Entities.Binder", b =>
                {
                    b.Navigation("PokemonCard");
                });
#pragma warning restore 612, 618
        }
    }
}
